### ISSUE TITLE
Additional Option to warn/caution user on a warn event as : toast.warn()

### ISSUE THREAD

**Issue by chimmy-changa** [timolins/react-hot-toast#102]
We have an option to notify user on a success or warn event. But we do not have any option to notify user as a warning/ caution event.

success event has a green tick icon :  :heavy_check_mark: 
error event has a red cross icon:  :x:

warn/caution event can have a yellow caution icon such as this : :warning:

**Comment by timolins** [comment]
Duplicate of #29
