### ISSUE TITLE
Make it easier to work with Tailwind

### ISSUE THREAD

**Issue by DavidRouyer** [timolins/react-hot-toast#105]
I'm trying to customize my toasts with Tailwind, but I'm currently struggling with the default styles. I'm trying to override the styles with Tailwind but I can't remove the default classes:

```javascript
export const Toast: React.FunctionComponent<ToastProps> = ({
  position = 'bottom-center',
  toastOptions = {
    className: 'text-xs font-semibold rounded-lg p-2',
    success: {
      icon: null,
      className: 'text-xs font-semibold rounded-lg p-2 bg-green-300 text-green-900',
    },
    error: {
      icon: null,
      className: 'text-xs font-semibold rounded-lg p-2 bg-red-300 text-red-900',
    },
  },
  ...props
}: ToastProps) => {
  return (
    <Toaster position={position} toastOptions={toastOptions} {...props}>
      {(t) => (
        <ToastBar toast={t} position={position}>
          {({ message }) => (
            <>
              {message}
             
            </>
          )}
        </ToastBar>
      )}
    </Toaster>
  );
};
```

But they are overrided with those styles https://github.com/timolins/react-hot-toast/blob/d1456c4e4fdc8210f24b08334a2a464efa815eb0/src/components/toast-bar.tsx#L21-L33 and I can't even override those ones (remove margin) https://github.com/timolins/react-hot-toast/blob/d1456c4e4fdc8210f24b08334a2a464efa815eb0/src/components/toast-bar.tsx#L35-L41
Please think about removing those default styles so we can easily theme them by adding classes and styles or by adding an extra div.

**Comment by DavidRouyer** [comment]
Closing this, I'm using the Custom Rendered API to easily manipulate the HTML structure and the associated classes

**Comment by lavgup** [comment]
> Closing this, I'm using the Custom Rendered API to easily manipulate the HTML structure and the associated classes

Could you please expand on how you solved this issue? Would really help me as I'm using Tailwind for my site as well.

**Comment by chrisrobbins** [comment]
@DavidRouyer I am having this same issue, can you provide a little guidance as to how you fixed it? Nothing is turning up for me for Custom Rendered API.

**Comment by timolins** [comment]
@chrisrobbins  Have a look at this example, which uses the Custom Renderer API, TailwindCSS & HeadlessUI for easy animations: https://codesandbox.io/s/react-hot-toast-tailwindcss-headless-ui-qvjri?file=/src/App.js

**Comment by DavidRouyer** [comment]
I made my own `<Toaster />` component so I could style anything the way I wanted
