### ISSUE TITLE
Request: Export types

### ISSUE THREAD

**Issue by alii** [timolins/react-hot-toast#114]
Would it be possible to have the types exported? Right now I have to do the following to wrap `toast()`:
![image](https://user-images.githubusercontent.com/25351731/130453168-a2dd5b20-a0ee-4767-86c1-f5f30d116c15.png)

It would be nice to import them all in the same import.

Here's my usage:
![image](https://user-images.githubusercontent.com/25351731/130453234-5d841d90-a89f-4107-9a8e-c63f2d3ccbea.png)

**Comment by heybereket** [comment]
Yeah.

**Comment by timolins** [comment]
Those types are now available with https://github.com/timolins/react-hot-toast/releases/tag/v2.2.0. 🙌

**Comment by alii** [comment]
Woohoo!!! Thank you!!
