### ISSUE TITLE
How To Dismiss or remove the toast when redirect to new page

### ISSUE THREAD

**Issue by kailaskadam** [timolins/react-hot-toast#120]
Hi,

I am using the react-hot-toast for showing the notification in my app. It works very nicely.

The only issue I am facing now is, I am showing the toast for 3 seconds. If somebody jumps to other routes or pages, he is able to see the toast on the new page until the 3 seconds.

So, how can I dismiss the toast when the user redirects the new page.

This is the toaster i a using in app.js.As the document suggests i am using only one toast for the entire app.

   <Toaster position="top-center" toastOptions={wishlistToaster} />

This is the function i am calling to remove the toast in app.js
  toast.remove();

but it's not working?

Thanks
Kailas

**Comment by timolins** [comment]
You can try to dismiss all toasts on navigation. For example, this could be done with `useEffect`.
```jsx
const App = () => {

  useEffect(() => {
   // Dismiss all active toasts
   toast.dismiss()
  }, [currentRoute])

  return ( ... )
}
```

_Originally posted by @timolins in https://github.com/timolins/react-hot-toast/discussions/26#discussioncomment-289141_
