### ISSUE TITLE
Position toast individually (TBRL included).

### ISSUE THREAD

**Issue by Raj2631** [timolins/react-hot-toast#125]
I wanted to change position of toast individually, but only thing i was able to find was the [Individually position toasts](https://react-hot-toast.com/docs/version-2#per-toast-positioning) documentation. 
But  I wasn't able to find how to change the TBRL position of the toast too. Is there a way to do that? Wasn't able to understand through the docs if that was possible or not.

I want to have toasts with same position (top-right in my case) but I want to be able to change the offsets of the toasts individually (example one toast could be 50px from top, other may be 100px).

**Comment by timolins** [comment]
You can change the offset for toasts as well as the space between them. Doing this on a per-toast basis is not supported, as this would break the stacking logic.

```jsx
<Toaster
  gutter={20} // Space between toasts
  containerStyle={{
    top: 50, // Offset at the top
    right: 50 // Offset to the right
  }}
/>
```
