### ISSUE TITLE
Toast should remain fixed on scroll at all times.

### ISSUE THREAD

**Issue by pzapo** [timolins/react-hot-toast#126]
On scroll down it goes up and then switches back to bottom bar of the view.
On scroll up it hides with the view and the reaper at the bottom bar.

Is there way to set up toast to be fixed at all times?

**Comment by stephanbogner** [comment]
This doesn't happen to me. How did you include `<Toaster/>` in your code?

**Comment by timolins** [comment]
This seems to work for me. Please provide an example so we can reproduce. I'll close this issue for now.

**Comment by remorses** [comment]
In my case this was caused by `contain: paint` css prop which basically converts `absolute` positioned elements to `relative`
