### ISSUE TITLE
Allow customization of message container

### ISSUE THREAD

**Issue by timolins** [timolins/react-hot-toast#13]
This issue was original raised by @ambroseus in #5. It would be cool to replace the built-in Message container. It includes styles which are hard to get rid of at the moment.

Ideally you will be a able to provide a custom Component without having to go headless.

**Comment by OlaoluwaM** [comment]
Hello

This project looks really cool! Could take a go at this issue?

**Comment by provinceinnovation** [comment]
Really keen on the ability to style that `<Message>` component. Would be great if we could just add a `messageStyle` key to the current toast options e.g.

````
toast(<MyComponent />, {
  id: 'component-id',
  duration: 5000,
  style: { 
    padding: 0,
  },
  messageStyle: {
    margin: 0,
  }
});
````

What do you think - would you like me to open a PR for this?

**Comment by lsbyerley** [comment]
This is a very needed customization as the the current styling for the toast container isn't customizable. I agree the `messageStyle` or maybe even `toastContainerStyle` property would be a solid solution to add

**Comment by lsbyerley** [comment]
I do see this `containerStyle` property in the Toaster component but I don't think it does anything?

https://github.com/timolins/react-hot-toast/blob/7e4391db1908ff0168bacd87beda115408b76ce0/src/components/toaster.tsx#L22
