### ISSUE TITLE
How do I enable clicking the Toast icon to close / dismiss ?

### ISSUE THREAD

**Issue by ajoslin103** [timolins/react-hot-toast#131]
I can't figure out how do I enable clicking the Toast icon to close / dismiss ?

**Comment by MatteoBuffo** [comment]
Same question, but I'm using custom JSX content toasts.

**Comment by timolins** [comment]
Here is an example how you can implement click to dismiss: https://codesandbox.io/s/react-hot-toast-click-to-dismiss-nbztn

Does that work for you?

**Comment by bruno-silva5** [comment]
I now its closed, but, just adding a simple way of also doing the same thing:

```
const id = uuid();

toast(<Button onClick={() => toast.remove(id)}><X /></Button>, {
    id,
    duration: 2000,
})
```
