### ISSUE TITLE
Toast height calculation bug

### ISSUE THREAD

**Issue by danqing** [timolins/react-hot-toast#133]
Example: https://codesandbox.io/s/react-hot-toast-responsive-position-forked-64f33?file=/src/App.js

<img width="511" alt="Screen Shot 2021-11-17 at 3 38 38 PM" src="https://user-images.githubusercontent.com/5134133/142278835-dc833929-b18f-4dcc-94d0-efea83cacc82.png">

When you use the toast ID to change one toast to another (e.g. from loading to success), sometimes the height of the toast is off. I think it's because it's not updating the height of the toast container when the content changed.

(As always, thank you for this great lib!)

**Comment by timolins** [comment]
Great find, this is indeed a bug. The height of each toast is currently only measured on mount. The fix requires a bit of a refactoring, I will have a closer look when I get to it.

**Comment by swiftyjam** [comment]
Hey! Hows the progress on this @timolins ? ❤️

**Comment by alexfertel** [comment]
Not sure if this is appropriate, but it would be very nice if this got fixed! Thanks for an awesome lib!

**Comment by valdrin-t** [comment]
Is there a way to force recalculation of the heights? I'm getting the same issue with `toast.custom` where the custom toaster can expand/shrink

**Comment by timolins** [comment]
@valdrin-t Not in the current version. This should be fixed with  #207. Trying to get this out soon.

**Comment by valdrin-t** [comment]
Cool! I didn't notice the PR was still open, I thought it was merged.

**Comment by liho00** [comment]
> ```css
> .wrapper {
>   display: flex;
>   flex-direction: column;
> }
> .wrapper > div {
>   position: relative !important;
>   transform: translateY(0) !important;
> }
> ```

this method working, however dismissing the toast will be delay, have to use toast.remove to remove the toast, thus, this will also causing the animation of remove toast gone...
