### ISSUE TITLE
toast text alignment

### ISSUE THREAD

**Issue by ATakaSKY** [timolins/react-hot-toast#136]
I want the toast text to be left aligned instead of center, this is what I'm trying to do:

```
toast('My toast.', {
              duration: 2000,
              position: 'bottom-center',
              style: {
                background: '#ccc',
                width: '300px',
                textAlign: 'left',
              },
              icon: '😀',
            });
```

What this ends up creating is this:
<img width="275" alt="image" src="https://user-images.githubusercontent.com/17201629/143071864-3fbe7102-178d-4281-80d2-9f564d2afddf.png">

What I instead want is:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/17201629/143071947-3ffd6280-3867-43f1-8d4b-d9c2944c3c55.png">

Is there some way to make this work

**Comment by timolins** [comment]
You can find two possible solutions here: https://github.com/timolins/react-hot-toast/issues/88#issuecomment-863131815

If this is something more people want, we can think about exposing an API for that.
