### ISSUE TITLE
Limiting amount of Toasts

### ISSUE THREAD

**Issue by RomanFausek** [timolins/react-hot-toast#137]
Hi, is it possible to declare a maximal number of toasts that can be visible at one time?

Example:
someone will trigger 5 toasts but only the last 3 will be visible
or
adding them to queue

**Comment by timolins** [comment]
This is currently not possible, but there is a possible solution in #31.
If you think this should be a feature of RHT, feel free to mention that in the issue.

**Comment by RomanFausek** [comment]
Thank you for the quick answer. Didn't notice this thread. Love it! 🚀
