### ISSUE TITLE
Support for max count on <Toaster> 

### ISSUE THREAD

**Issue by mcintyre94** [timolins/react-hot-toast#140]
It'd be useful to be able to set a maximum number of toasts that are displayed at a time. I think this could quite easily be done using the `useToaster` hook, but it'd be nice to have support for it in `<Toaster>` as well so we can use it without having to do our own rendering.

Eg from the homepage:

<img width="1473" alt="Screenshot 2021-12-13 at 10 27 12" src="https://user-images.githubusercontent.com/1711350/145796750-130d7b6b-46ea-4e25-bee0-93d4147177e8.png">

I'd be happy to write a PR for this!

**Comment by haneenmahd** [comment]
I think there is a limit
https://github.com/timolins/react-hot-toast/blob/09ded7fae2d0d6b3bc786fea9239f86fb691465d/src/core/store.ts#L4

but it would be awesome to have custom limit at a time

**Comment by timolins** [comment]
Thanks for the suggestion! Closing this in favour of #31, which includes a workaround for now. Planing to include a proper API for this in the next release.
