### ISSUE TITLE
bug: toast.promise() gets stuck in loading state

### ISSUE THREAD

**Issue by zacronos** [timolins/react-hot-toast#142]
This might be related to #101.

When using `toast.promise()`, sometimes the loading toast will remain forever, even once it should have transitioned to the `success` toast.  The `loading` toast then clears the next time a toast is triggered, and toasts seem to behave correctly after that.

I tried changing my code to make individual calls to `toast.loading()`, `toast.success()`, and `toast.error()` with the `toastId` as shown in the documentation, but that doesn't seem to help.  In this format, I've even added some calls to `console.log()` to see that I'm calling `toast.success()` with a valid toastId.

For instance, with the below code, even once I see the success message from `console.log()`, I continue to see the loading toast:
```
const toastId = toast.loading('Saving...');
console.log(`@@@@@@@@@@@@@@@@@@@@ toasted ${toastId}`);
try {
  await doSomethingAsynchronous();
  console.log(`==================== success! ${toastId}`);
  toast.success('Project saved!', {id: toastId, duration: 1000});
} catch (err) {
  console.log(`==================== error! ${toastId}`);
  toast.error('Error saving project!', {id: toastId, duration: 6000});
}
```

I just realized this only seems to happen if I use `toast.promise()` or `toast.loading()` for the first toast triggered on a given pageload.  (I think.)  So now I tried putting this in my app's root component, and it seems to be a workaround for now:

```
useEffect(() => {
  toast.success('', {duration: 1, style: {display: 'none'}})
}, []);
```

**Comment by zacronos** [comment]
The workaround above didn't entirely fix the issue after all.  But I did discover that mousing over the loading toast causes it to transform into the toast that should be displaying.

**Comment by zacronos** [comment]
Actually -- it seems that the workaround above works for `toast.promise()` calls _which will resolve successfully_, but not calls that result in an error.  The code below seems to prime `toast.promise()` for both success and error results, and so is a more complete workaround:

```
useEffect(() => {
  toast.success('', {duration: 1, style: {display: 'none'}})
  toast.error('', {duration: 1, style: {display: 'none'}})
}, []);
```

**Comment by alii** [comment]
Is it possible to have a minimal reproduction repo? I've never experienced this behaviour before

**Comment by zacronos** [comment]
I'm not sure I can easily reproduce this any more.  It seems this behavior was tied in with some major state/rendering issues I had for a bit.  So it was likely just a symptom of a problem in my app rather than a problem with this library.
