### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by Luccasoli** [timolins/react-hot-toast#143]
There is some PRs which fix some bugs that still open with no reviews :(

**Comment by timolins** [comment]
Nope, still alive. 👍
Planing for a new release soon. Any specific PR you want to be resolved?

**Comment by Luccasoli** [comment]
@timolins Yes, #118 i was trying to create a facade component and the lack of types was making things difficult

Thanks!

**Comment by timolins** [comment]
Whoops, thanks for bringing that up again. Just merged, will try to release asap.
