### ISSUE TITLE
How can we use toast.custom but with a promise?

### ISSUE THREAD

**Issue by craftogrammer** [timolins/react-hot-toast#147]
I check the documentation about styling with tailwindcss, but I was looking for an example with toast.custom(t) and having a promise?

**Comment by timolins** [comment]
This is currently not possible. My suggestion would be to create a custom toaster, which will also apply for `toast.promise()`.


You can find mote information + example (with goober/style-components) here:
https://github.com/timolins/react-hot-toast/issues/67#issuecomment-983611798


This example with TailwindCSS + HeadlessUI (for easy transition animations) could be relevant as well: https://codesandbox.io/embed/react-hot-toast-tailwindcss-headless-ui-qvjri


Does this work for you?
