### ISSUE TITLE
How to make message in two line?

### ISSUE THREAD

**Issue by hibangun** [timolins/react-hot-toast#149]
I want alert message to become 2 line like this
![image](https://user-images.githubusercontent.com/16166419/149851129-42c60b37-4bdc-419f-9463-4b3fc6c5ced2.png)

Does anyone know how to do that?

I can actually using `\n` like
```
toast.success('Successfully saved!\nAnyone with a link can now view this file')
```
but I need to style the first row to be bold, and change the font color in second row

**Comment by timolins** [comment]
You can pass in JSX to achieve this.
```jsx
toast.success(() => (
  <div>
    <b>Successfully saved!</b>
    <p>This is a subtitle</p>
  </div>
))
```
