### ISSUE TITLE
Different toast position based on screen size

### ISSUE THREAD

**Issue by danbeneventano** [timolins/react-hot-toast#15]
For example, I want the toast to show at `bottom-center` for mobile devices (width < 640px), but `top-right` for laptop/desktop

**Comment by albannurkollari** [comment]
> For example, I want the toast to show at `bottom-center` for mobile devices (width < 640px), but `top-right` for laptop/desktop

You can easily implemenr your solution if you refer to this short blog https://css-tricks.com/working-with-javascript-media-queries/.

Basically, you listen to media query changes for that custom media selector and then when that  is applied, supply a different toaster position within the callback.

**Comment by timolins** [comment]
@albannurkollari is right! This is a great use case for the matchMedia API.

Check out this [demo codesandbox](https://codesandbox.io/s/react-hot-toast-responsive-position-rh276?file=/src/App.js) which implements the behaviour you want :)
