### ISSUE TITLE
Toast is flashing repeatedly

### ISSUE THREAD

**Issue by rwc0920** [timolins/react-hot-toast#152]
After clicking on a button to activate the toast. It will continuously flash and not stop. The only parameters I'm passing in to <Toaster /> is duration and position.

![savedPrograms](https://user-images.githubusercontent.com/66286416/153083732-fd6e6da6-5f5f-42e7-9d09-3a4e9090119d.gif)

**Comment by timolins** [comment]
Can you provide an example which reproduces this?

**Comment by potapovnikita** [comment]
The same error. Reproducing with a few Toasts providers, which used in microservices. Toaster component should be a singleton component.
