### ISSUE TITLE
Loading state for multiple promise

### ISSUE THREAD

**Issue by francochau** [timolins/react-hot-toast#161]
```
toast.promise(
      e.then((res) => res.wait()),
);
```
Everything are working fine except the loading toast disappear when e resolved.
Success message can be shown once wait() done.
Any idea?

**Comment by timolins** [comment]
That should not be the case. Can you show a working example that reproduces this?

All react-hot-toast does behind the scenes is append a "then" to your promise, which triggers the success toast.
Maybe `res.wait()` doesn't do what you expect.

I'll close this until this can be verified.
