### ISSUE TITLE
Forcing remove of one toast prevents all subsequent auto-removal of toasts

### ISSUE THREAD

**Issue by satuhyva** [timolins/react-hot-toast#169]
I have created custom toasts that contain a button with which the toasts can be removed (using the toast.remove-function and the respective toast id).  When any toast is created, a default duration is set. If I keep creating new toasts (but do not remove them by clicking), the toasts appear and auto-disappear as guided by the set duration. 

However, if I click one toast remove-button, the toast in question disappears but as an undesired extra effect all subsequent toasts lose their ability to auto-remove (and all currently existing or later created toasts have to be removed by clicking the button).

**Comment by scream87** [comment]
@satuhyva 
Then you hover on toast with mouse (or tap it with finger on mobile), toast will set a global pause state. This will prevent all active toasts from closing, untill state will be unpaused again. Unpausing will happen then you hover out of the current hovered toast (or tap in some other place in mobile). The source of problem seems to be in that after button was clicked pause ending is not happening automatically. It can be unpaused if you hover/unhover on an other visible toast or you can do it programmatically via toast API.
Via API - import `useToaster` hook - https://react-hot-toast.com/docs/use-toaster and then use `handlers.endPause` right after `toast.dismiss`. This works for me.
