### ISSUE TITLE
Is it possible to have blocking for toasts, so only 1 is renderred?

### ISSUE THREAD

**Issue by ajaypillay** [timolins/react-hot-toast#18]
As the title suggests, is it possible to limit the number of toasts displayed to some integer value? So subsequent triggers of `toast()` will be blocked. I did not come across anything in the docs which implied this, so I was wondering if there's any way to implement this. Thanks! (great package by the way!)

**Comment by timolins** [comment]
Setting an integer limit is currently not possible. What is possible though is that  you can provide a fixed `id` to your toast. This will prevent concurrent toasts of the same kind.

```js
toast("Copied to clipboard.", {
	id: "copy"
})
```

Would that work for your use-case?
