### ISSUE TITLE
ppnm missing peer dependencies csstype@^3.0.10

### ISSUE THREAD

**Issue by backtolife2021** [timolins/react-hot-toast#182]
![image](https://user-images.githubusercontent.com/24669431/167404205-aabe6edb-3689-4b89-8115-c246c3bf27e6.png)

**Comment by eeston** [comment]
I've raised a fix here...
https://github.com/timolins/react-hot-toast/pull/183

**Comment by dvrfluxchat** [comment]
Still facing this issue. 

 WARN  Issues with peer dependencies found
apps/dashboard
└─┬ react-hot-toast 2.4.0
  └─┬ goober 2.1.12
    └── ✕ missing peer csstype@^3.0.10
Peer dependencies that should be installed:
  csstype@^3.0.10
