### ISSUE TITLE
Improve dev dependency linking (Upgrade to latest NPM)

### ISSUE THREAD

**Issue by timolins** [timolins/react-hot-toast#186]
Currently I'm using NPM v6 for react-hot-toast and it's site, because I'm running into a dependency issue otherwise.

The `./site` has a local dependency on package in the parent directory. https://github.com/timolins/react-hot-toast/blob/main/site/package.json#L22

For a reason I don't fully understand yet, I get this error while loading the demo site. However, this is only the case when I use a "newer" package manger like yarn, pnpm and npm 7 & above.

NPM v6 doesn't cause this issue, which is the workaround I've been using.

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

### Resources
This issue seems to be related. I haven't found a solution though. https://github.com/vercel/next.js/issues/9022

Getting rid of this caveat makes sense moving forward, as it adds friction to most incoming PR. If anyone has experience with this, please let me know!

**Comment by eeston** [comment]
Until this is resolved, it may be worthwile adding [`npm` to `engines`](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#engines) for a bit of visability...

**Comment by timolins** [comment]
Finally got this resolved 🚀
