### ISSUE TITLE
React Native: Unable to resolve "goober"

### ISSUE THREAD

**Issue by nephix** [timolins/react-hot-toast#194]
When running `react-hot-toast` in RN I get the following error:

```
iOS Bundling failed 1110ms
Unable to resolve "goober" from "../../node_modules/react-hot-toast/dist/react-hot-toast.cjs.production.min.js"
```

It's a monorepo and `../../node_modules/goober` exists

**Comment by timolins** [comment]
Thanks for bringing this up. This is a known issue and is track here #39
