### ISSUE TITLE
Dismiss and duration don't work on a custom toast

### ISSUE THREAD

**Issue by benjamin-benoit** [timolins/react-hot-toast#199]
Hello, I did a custom toast using a component:

`toast.custom(<ScheduledToaster />);`

But I can't use the duration like that:

`toast.custom(<ScheduledToaster />, { duration: 10000 });`

And I can't use toast.dismiss(), to remove all custom toasts, only toast.remove() is working.

**Comment by peniqliotuv** [comment]
+1 to this - only calling `toast.remove()` and `toast.remove(id)` is working for me as well -- I'm using `toast()` instead of `toast.custom()` though

**Comment by timolins** [comment]
Is it possible that it works, but is delayed for 1 second?
This is because toast.dismiss() doesn't remove the toast instantly. It waits for one second in order to leave room an unmount animation. `toast.custom()` currently doesn't apply any animations – #116.

You can react to `t.visible` to hide it yourself.

**Comment by timolins** [comment]
Can you please provide an example which reproduces this issue? It works fine on my end: https://codesandbox.io/s/react-hot-toast-custom-toast-dismiss-re8xhs

**Comment by AngheloGc** [comment]
Hi. I also ran into this issue. Here I have replicated the case:
https://codesandbox.io/s/react-hot-toast-dismiss-and-duration-bug-krbt1p?file=/src/TestView.tsx

**Comment by brandonpittman** [comment]
I'm doing something like this with Framer Motion and it's working well.

Toast caller:
```tsx
  useEffect(() => {
    if (message) {
      toast.custom(
        (t) => (
          <Notification
            isVisible={t.visible}
            onDismiss={() => toast.dismiss(t.id)}
          >
            {message}
          </Notification>
        ),
        { duration: 20000 }
      );
    }
  }, [message]);
```

Notification component:
```tsx
<AnimatePresence>
  {isVisible && (
    <motion.div
      key="notification"
      initial={initial}
      animate={animate}
      exit={exit}
      role="alert"
    >
  </motion.div
</AnimatePresence>
```

**Comment by brandonpittman** [comment]
> Can you please provide an example which reproduces this issue? It works fine on my end: https://codesandbox.io/s/react-hot-toast-custom-toast-dismiss-re8xhs

In this example, because `t.visible` starts as `true`, the enter transition does nothing. It just pops into existence. The exit transition does work because RHT waits 1 second before removing the element from the DOM.

**Comment by seanmcquaid** [comment]
Also seeing this as well with custom toasts. For now, I am just using a useEffect in the custom component to clear the toast.

**Comment by deepaktammali** [comment]
We are facing this issue as well with custom toasts.

**Comment by kylegillen** [comment]
+1

**Comment by felipemullen** [comment]
There is definitely something strange happening on custom toasts. In my case, calling `toast.custom` causes the popup to occasionally hang unless I change to another tab or mouse over the browser's inspector window:

```javascript
toast.custom((t) => <PlayerWinsHand winningPlayer={player} toast={t} />, { duration: 1250 });
```

I have to manually dismiss using `toast.dismiss`

**Comment by angeld287** [comment]
`(t) => (
			<ActionAlertCard
				onClickAction={() => {
					onClickAction();
					toast.remove(t.id);
				}}
				icon={<WarnIconYellow />}
				{...{ text, date, buttonText }}
			/>
		)`

toast.remove worked for me!

**Comment by atNeerajShukla** [comment]
toast.custom((t: Toast) => {
  <button onClick={() => toast.remove(t.id)}>
    Close Button
  </button>
});

Use toast.remove(toastID) instead of toast.dismiss, as it is faster and more efficient.
