### ISSUE TITLE
Can i use it with React Native?

### ISSUE THREAD

**Issue by bornmay** [timolins/react-hot-toast#2]
Hii, React Hot Toast team, I see this project to be really awesome and an example of really good work.

Is the React Hot Toast add on Stable or useable for React Native?

**Comment by timolins** [comment]
Hey! Thanks for bringing react-native up. Dropping it in won't work right now, but you can use headless mode (`useToaster()`) to create your own notifications. I build a quick demo on expo: [Showcase useToaster() with react-native](https://snack.expo.io/@timo/react-hot-toast---usetoaster()---react-native)
