### ISSUE TITLE
Custom toast flicker before leaving with custom animation

### ISSUE THREAD

**Issue by naveenkash** [timolins/react-hot-toast#206]
I'm having a issue with custom toast i added the animation but before leaving it flicker and come back to enter animation. here's the sandbox - https://codesandbox.io/s/sleepy-galois-bdhw3m?file=/src/App.js

**Comment by timolins** [comment]
Duplicate of #165.

Try adding `forwards` keyword to your exit animation, which preserves the final state (which is hidden). Otherwise it will jump back to the initial state after the animation ended.

**Comment by naveenkash** [comment]
Thank you It fixed the issue
