### ISSUE TITLE
Feature request: convert Type and Position to enum

### ISSUE THREAD

**Issue by mkbctrl** [timolins/react-hot-toast#212]
Hey, I wanted to ask what do you think about converting the:

```
declare type ToastType = 'success' | 'error' | 'loading' | 'blank' | 'custom';
declare type ToastPosition = 'top-left' | 'top-center' | 'top-right' | 'bottom-left' | 'bottom-center' | 'bottom-right';
```

into enums?

That way we can use the enum in a code like:

```
import { ToastPosition } from 'react-hot-toast';

/**
 * @description default configuration for all toast notifications
 **/
export const defaultToastOptions = {
  position: ToastPosition.BottomLeft,
  reverseOrder: false,
  gutter: 10,
  containerStyle: { bottom: 100, left: 20 },
  toastOptions: { duration: 2000 },
}
```

which seems more type safe. I am happy to create PR, if you like this idea.

**Comment by timolins** [comment]
Hi! In this case I prefer the string constants for a few reasons:
- More intuitive for JS users
- Doesn't require an additional import
- It's type-safe & works with auto-complete
- The string content is used in the logic as well. (Check if it contains top or bottom)
