### ISSUE TITLE
Possible for toast to appear near mouse click position?

### ISSUE THREAD

**Issue by ADTC** [timolins/react-hot-toast#229]
My idea is to have a toast appear near (above, below, left, right or on-top) the mouse-click position when the click was done on an action, so that the toast has an "Undo" button to reverse the action.

Would this be possible somehow? Note that there are multiple actions, dynamically generated (like a table with rows). Hopefully you won't say I have to put a `<Toaster>` next to every action button and use `relative` position. 😆 I'd rather just have the toast appear where the mouse click was or where the mouse pointer is.

 (Same applies for finger tap on touchscreens.)

**Comment by ADTC** [comment]
Also, how could I implement a Toast with an "Undo" button which would somehow cancel a pending action?

**Comment by c-eiser13** [comment]
@ADTC came across this issue looking for something else, but I had this exact requirement and used a custom hook to return the x/y coordinates of the click and used the Toaster containerStyle prop to implement.

hook:
![image](https://user-images.githubusercontent.com/42096464/202560611-53826e15-aaf4-4fef-a3af-1e964c207f41.png)

In the component:
![image](https://user-images.githubusercontent.com/42096464/202560697-ea09ed1a-a85a-466c-91f1-d65823a5584c.png)

finally, the Toaster:
![image](https://user-images.githubusercontent.com/42096464/202560837-fd73504c-9b1b-433d-ab2c-0daaffb9f54d.png)

The div with the ref wraps all my JSX where clicks can happen. Hope this helps...
