### ISSUE TITLE
Don't apply lib default styles (`go...`) when using custom JSX

### ISSUE THREAD

**Issue by mkosir** [timolins/react-hot-toast#230]
I want to style toast component with custom styles/components, where default ones (prefixed as `go...`) are being injected (background color etc.). I understand some of them are necessary for example animation, position etc.

![image](https://user-images.githubusercontent.com/3073826/198034904-d3ddc8dd-8c21-4bdd-b950-e09143351cff.png)

**Comment by AsadSaleh** [comment]
Same Here!

**Comment by timolins** [comment]
How are creating the custom toast? Have you tried using providing a [custom render function](https://react-hot-toast.com/docs/toaster#using-a-custom-render-function)? This way, it should apply the required styles for positioning.

I'll close this for now.
