### ISSUE TITLE
custom toast with custom animation not working

### ISSUE THREAD

**Issue by SyFlo** [timolins/react-hot-toast#241]
I'm trying to get a custom toast (i.e. creates with `toast.custom(...)` to work with a custom animation. Following the example in https://react-hot-toast.com/docs/styling ("Change enter and exit animations") it isn't clear to me in what form "custom-enter" and "custom-exit" need to be provided. I'm not using tailwind, so what I tried was to define keyframes as follows:

```
@keyframes custom-enter {
    from {
        transform: translateX(0%);
    }

    to {
        transform: translateX(100%);
    }
}
@keyframes custom-exit {
    from {
        transform: translateX(100%);
    }
    to {
        transform: translateX(0%);
    }
}

```
```
together with

import { Toaster, ToastBar } from 'react-hot-toast';

<Toaster>
  {(t) => (
    <ToastBar
      toast={t}
      style={{
        ...t.style,
        animation: t.visible ? 'custom-enter 1s ease' : 'custom-exit 1s ease',
      }}
    />
  )}
</Toaster>;

```

but that didn't work - the animation just isn't applied to the ToastBar. Could anyone provide a working example of custom animations with pure CSS or some form of CSS-in-JS (e.g. styled-components)?
Thank you 🙏

**Comment by timolins** [comment]
Here is an example with CSS-in-JS and custom animations: https://codesandbox.io/s/react-hot-toast-custom-toasts-with-styled-components-i4xj6

Hope this helps.

**Comment by SyFlo** [comment]
Thank you so much for the quick reply and the example code 🙏 I tried to adapt this to my use case, but it still doesn't work. I haven't yet figured out whether that is because I'm using the `toast.custom()` function which you are not using in your example or because I'm now mixing styled-components from my code with goober from your example. I'll try to fork your example in codesandbox and strip out everything that doesn't seem related to the question of custom animations (i.e. the random promise etc) so that it resembles my use case more closely. maybe that helps me understand what exactly I need to do to create a custom animation (preferably using the "keyframes" function from styled-components rather than goober) that works with `toast.custom`. Of course, any hints would be greatly appreciated.

```
const BaseToast = styled.div`
  background: #333;
  border-radius: 5px;
  color: #ddd;
  display: flex;
  align-items: center;
  padding: 5px;
  padding-right: 10px;
  width: 200px;
  height: 30px;
`;

const enterAnimation = keyframes`
 from {
   opacity: 0;
   transform: translateY(-30px);
 }
 to {
   opacity: 1;
   transform: translateY(0px);
 }
`;

const exitAnimation = keyframes`
 from {
   opacity: 1;
   transform: translateX(0px);
 }
 to {
   opacity: 0;
   transform: translateX(100%);
 }
`;
export const NotificationToaster = (): JSX.Element => {
  return (
    <Toaster
      position="top-right"
      toastOptions={{
        custom: {
          duration: 5000,
        },
      }}>
      {(t) => (
        <BaseToast
          style={{
            animation: t.visible
              ? `${enterAnimation} 0.2s ease-out forwards`
              : `${exitAnimation} 0.4s ease-in forwards`,
          }}>
          <ToastBarContent>
            <MessageWrapper>{t.message as string}</MessageWrapper>
          </ToastBarContent>
        </BaseToast>
      )}
    </Toaster>
  );
};
```

**Comment by SyFlo** [comment]
@timolins Sorry, but I wouldn't regard this issue as closed. Would you mind answering my question? Is there a way to use custom JSX but apply an animation?

**Comment by williamtobing** [comment]
I'm facing the same issue with the toast.custom
