### ISSUE TITLE
Add warning message

### ISSUE THREAD

**Issue by jeevasusej** [timolins/react-hot-toast#249]
Here I can find success and error but not warning. 

1. Good to have warning type
2. Good to have header for error message
3. Good to implement close all error message if we have more than one
4. Good to pass additional values with success, warning, custom etc.. If we implement our own wrapper, This will be useful. Now I am sending additional params like 
```
 toast.success('This is success message', {
      heading: 'Heading text',
    } as any);
```

`  toast('This is warning message', { type: 'warning' } as any);`

**Comment by jack75015** [comment]
+1 for the warning message :)

**Comment by huazhuangnan** [comment]
https://github.com/timolins/react-hot-toast/issues/29 @jeevasusej  @jack75015

**Comment by Nitinkumar2905** [comment]
toast.warning("this is a warning message")
 this can be much better

**Comment by timolins** [comment]
Closing in favour of #29
