### ISSUE TITLE
Use react hot toast promise without success message

### ISSUE THREAD

**Issue by manojgetwealthy** [timolins/react-hot-toast#264]
There is no way to use react hot toast with a promise that should not show any success message but only show error message or loading message.

Tried following but typescript gives error:

    ```
toast.promise(promise, {
                                    loading: 'Uploading doc..',
                                    error: 'Error uploading documents. Please try again after sometime'
                                });
```

Note: React host toast is awesome by the way.

**Comment by n33pm** [comment]
#179

**Comment by rcbevans** [comment]
Came to look for this, but for without error message (I want promise to be cancellable and in that case, skip an error toast)

**Comment by timolins** [comment]
Duplicate of #42
