### ISSUE TITLE
Is react-hot-toast compatible for Vue 2?

### ISSUE THREAD

**Issue by MadhabaPatra** [timolins/react-hot-toast#278]
I use this library for my react projects. Is this also supported for Vue 2?

If yes, then can someone please give me any doc reference/snippets to use it in Vue.
if no, Is there any alternative library for vue 2.

My problem statement is to show a "loading" toast and handle api call and update the "loading" toast to "success" or "error message" based on api response.

**Comment by timolins** [comment]
react-hot-toast is only available for react right, and I'm not aware of any alternatives. Feel free to post here if you find any.
