### ISSUE TITLE
How to avoid having multiple toasts on screen?

### ISSUE THREAD

**Issue by siyao-polarr** [timolins/react-hot-toast#289]
Is there an option to have a new toast replace the current toast instead of adding on?

**Comment by pandeymangg** [comment]
https://react-hot-toast.com/docs/toast

See the "prevent duplicate toasts" section

**Comment by camkon** [comment]
to limit the number of toasts shown on screen, customize the toaster component like

```
import { useEffect } from "react";
import toast, { Toaster, useToasterStore } from "react-hot-toast";

const ToasterComponent = () => {
    const { toasts } = useToasterStore();
    const TOAST_LIMIT = 1;

    useEffect(() => {
        toasts
            .filter((t) => t.visible) // Only consider visible toasts
            .filter((_, i) => i >= TOAST_LIMIT) // Is toast index over limit?
            .forEach((t) => toast.dismiss(t.id)); // Dismiss – Use toast.remove(t.id) for no exit animation
    }, [toasts]);

    return (<Toaster maxCount={1} />)
};

export default ToasterComponent
```
Hope this helps

**Comment by ivashchenko999** [comment]
> https://react-hot-toast.com/docs/toast
> 
> See the "prevent duplicate toasts" section

Would you kindly consider giving this thread a vote to help increase its visibility? Here's the [link](https://github.com/timolins/react-hot-toast/issues/294)

**Comment by myNameIsHamza** [comment]
Just call toast.dismiss() before toast.success or toast.error.

**Comment by telmodias** [comment]
☝️ I managed to achieve this by doing what @myNameIsHamza  indicated. Call `toast.remove();` just before doing the call to create a new toast. (ex. toast.success() or toast.error() ) .

**Comment by parth-patel-reversebits-25** [comment]
> to limit the number of toasts shown on screen, customize the toaster component like
> 
> ```
> import { useEffect } from "react";
> import toast, { Toaster, useToasterStore } from "react-hot-toast";
> 
> const ToasterComponent = () => {
>     const { toasts } = useToasterStore();
>     const TOAST_LIMIT = 1;
> 
>     useEffect(() => {
>         toasts
>             .filter((t) => t.visible) // Only consider visible toasts
>             .filter((_, i) => i >= TOAST_LIMIT) // Is toast index over limit?
>             .forEach((t) => toast.dismiss(t.id)); // Dismiss – Use toast.remove(t.id) for no exit animation
>     }, [toasts]);
> 
>     return (<Toaster maxCount={1} />)
> };
> 
> export default ToasterComponent
> ```
> 
> Hope this helps

Thank you so much this is working for me 👍
