### ISSUE TITLE
Custom output direction

### ISSUE THREAD

**Issue by gustavoalvim41** [timolins/react-hot-toast#329]
I would like to know if there is a way to customize the exit direction of Toaster, making them move to the right instead of the default upward direction.

```
<Toaster
  position="top-right"
  reverseOrder={false}
  containerStyle={{
    top: "11.2rem",
    position: "absolute"
  }}
  toastOptions={{
    style: {
      borderRadius: "0",
      boxShadow: "rgba(99, 99, 99, 0.2) 0 .2rem .8rem 0"
    },
  }}
/>
````

**Comment by sameer920** [comment]
I was just looking at the code and the issues and I think this can be achieved by modifying the exit animation. However, I still don't understand how you would want change the exit direction, maybe through props?

If the maintainers allow me, I will be willing to work on this as it seems like a cool feature to have when I use this library in future as well.

**Comment by timolins** [comment]
Yes you can customize the exit animation. The gist is to overwrite animation for the ToastBar when the toast's state changes to `visible: false`.

https://react-hot-toast.com/docs/styling#change-enter-and-exit-animations

```
import { Toaster, ToastBar } from 'react-hot-toast';

<Toaster>
  {(t) => (
    <ToastBar
      toast={t}
      style={{
        ...t.style,
        animation: t.visible
          ? 'custom-enter 1s ease'
          : 'custom-exit 1s ease forwards',
      }}
    />
  )}
</Toaster>;
```
