### ISSUE TITLE
Does toast() cause a re-render?

### ISSUE THREAD

**Issue by Blackglade** [timolins/react-hot-toast#33]
Hi, Found this a while back and am interested in using it for my next project. Building an SPA app and I have the Toaster set up like this:

index.js:
```jsx
import React from 'react';
import { Toaster } from 'react-hot-toast';

const queryClient = new QueryClient()
ReactDOM.render(
	<React.StrictMode>
			<BrowserRouter>
				<Routes>
					<Route path='/login' element={<Login />} />
					<Route path='/' element={<Dashboard />} />
				</Routes>
			</BrowserRouter>
			<Toaster />
	</React.StrictMode>,
	document.getElementsById('root')
);
```

Then in my login component I get an isError bool value back from my query and I have the following in my render component:

```jsx
return (
		<Layout>
			{isError && toast(error.toString())}
                         // render rest of content
)
```

I keep getting this issue:

index.js:1 Warning: Cannot update a component (`Toaster`) while rendering a different component (`Login`). To locate the bad setState() call inside `Login`, folow the stack trace as described in.

Anyway to get around this?

**Comment by timolins** [comment]
Yes, toast() does cause a re-render. In your code `toast()` get's called inside the render function which causes the issue.

Try wrapping the error handling inside a `useEffect()`:

```jsx
...

useEffect(() => {
  if (isError) {
    toast(error.toString())
  }
}. [isError, error]) 


return (<Layout> {/* ... */} </Layout>)
```

**Comment by DemaPy** [comment]
> Yes, toast() does cause a re-render. In your code `toast()` get's called inside the render function which causes the issue.
> 
> Try wrapping the error handling inside a `useEffect()`:
> 
> ```js
> ...
> 
> useEffect(() => {
>   if (isError) {
>     toast(error.toString())
>   }
> }. [isError, error]) 
> 
> 
> return (<Layout> {/* ... */} </Layout>)
> ```

For what reason you have written in your landing page: https://react-hot-toast.com/ call it anywhere?
Place, specify it in documentation somewhere.
