### ISSUE TITLE
how to support center-center?

### ISSUE THREAD

**Issue by sin911** [timolins/react-hot-toast#345]
`<Toaster
  position="top-left"
/>`
the position only has [top-left,top-center, top-right,bottom-left,bottom-center, bottom-right]
But I want to use  'center-center'
what should I do?Thanks

**Comment by 13RTK** [comment]
Just set the style fo the Toaster component

**Comment by timolins** [comment]
Like @13RTK suggested, you can change the `containterStyle` of your `<Toaster/>`.

```jsx
<Toaster
  containerStyle={{
    top: "50%",
  }}
/>
```

Here is a [demo](https://codesandbox.io/p/sandbox/react-hot-toast-issue-345-position-center-center-svw6mj?file=%2Fsrc%2FApp.tsx%3A1%2C1-13%2C1).

**Comment by Capsicum42** [comment]
Is there any chance to reach this goal using the hook
```
toast.success("Hallo World in center-center"{
something here ????
}
```

I just want to have some toasts in center-center. All others should stay right-bottom.

Regards
Holger

**Comment by uriva** [comment]
@timolins the issue is that we only want some of the toasts in the center not all of them, and it's not easy to change this css dynamically
