### ISSUE TITLE
Linear gradient background

### ISSUE THREAD

**Issue by xskipy** [timolins/react-hot-toast#347]
I would like to add linear gradient background to the toast

```tsx
<Toaster
   toastOptions={{
      style: {
          background: "linear-gradient(90deg, #123 0%, #456 100%)"
       }
   }} />
/>
```

However that does not seem to work currently.

**Comment by timolins** [comment]
Hi there! I tried reproducing and this works fine for me: https://codesandbox.io/p/sandbox/react-hot-toast-demo-q6ryq8?file=%2Fsrc%2FApp.tsx
