### ISSUE TITLE
[BUG] Crashed when an element with id `target` exists

### ISSUE THREAD

**Issue by vikiboss** [timolins/react-hot-toast#351]
- Package Version: v2.4.1
- [Codesandbox Reproduction](https://codesandbox.io/p/sandbox/react-hot-toast-demo-q6ryq8?file=%2Fsrc%2FApp.tsx%3A13%2C5)

<img width="1150" alt="image" src="https://github.com/timolins/react-hot-toast/assets/53367348/08f473e3-2cdf-4061-998e-6e5e6e59860c">

**Comment by akashMasih** [comment]
I am starting working on it
