### ISSUE TITLE
Website is down!!!

### ISSUE THREAD

**Issue by I-am-abdulazeez** [timolins/react-hot-toast#356]
The docs site is not working, 

hope everything is okay

**Comment by fellypsantos** [comment]
working here

**Comment by AnonSols** [comment]
The website is down, I cant access docs!!

**Comment by AnonSols** [comment]
> working here

it has never worked in my region, at least when I tried.

I visited it last two weeks, it didn't work. Checking again and seeing the same issues means it's something that urgently needs to be rectified

**Comment by fellypsantos** [comment]
> > working here
> 
> it has never worked in my region, at least when I tried.
> 
> I visited it last two weeks, it didn't work. Checking again and seeing the same issues means it's something that urgently needs to be rectified

try some VPN , if it works, contact your internet service provider and ask why this particular website is not working, I can confirm that is not a website fault, working normally here.

**Comment by timolins** [comment]
Closing for now, as this seems to be a regional problem outside of my control.
