### ISSUE TITLE
Add persistent toasts

### ISSUE THREAD

**Issue by hudochenkov** [timolins/react-hot-toast#36]
Sometimes we need to show toast until it's dismissed by user or programmatically. E. g. connection lost and notification is shown until it's back online. Or some long or slow process happens.

It is not always possible to use `toast.promise` for that. Currently I use very long duration to simulate persistent toast.

Is it possible to add persistent toast, which doesn't have any timers inside them? Then it would possible to do:

```js
const id = toast('No connection.', { persistent: true });

toast('Connected.', { id, persistent: false })
```

**Comment by timolins** [comment]
Would `{ duration: Infinity }` do the trick for you?

**Comment by hudochenkov** [comment]
Just tried. Toast won't even show. I tried both my custom toast and default one.

**Comment by timolins** [comment]
You are right. That's weird. I'll look into this.

**Comment by timolins** [comment]
Does `toast("Endless", { duration: -1 })` makes sense to you? Was the easiest fix I can think of, not sure if it's the best API though.

**Comment by joaopaulobdac** [comment]
@timolins I think it would be better to just do `if (isFinite(duration)) { set timeout }` and keep using the `{ duration: Infinity }` API.

**Comment by timolins** [comment]
Thanks for the feedback! I agree with you, using Infinity seems like the more intuitive API. Will update and merge the PR :)
