### ISSUE TITLE
Toast container is hided behind iOS virtual keyboard

### ISSUE THREAD

**Issue by tntchn** [timolins/react-hot-toast#360]
I'm using react hot toast to show form submit event payload checking on my website. When click the submit button in the form, I would like to show the error message with react hot toast.

Currently, the toaster container's style is set like this
```html
<div style="position: fixed; z-index: 9999; inset: 16px; pointer-event: none"></div>
```

The current behavior of my website is to focus on invalid input and show the toast message. However, when I used the website on Safari in iOS, the virtual keyboard open and the toast message was hided behind the virtual keyboard.

Is there any method to shrink the toast container division to the real viewport?

**Comment by timolins** [comment]
You can try setting the container max-height to `100dvh` which should adapt if the keyboard is open. Let me know if that helped
