### ISSUE TITLE
Speed Issue With NextJs

### ISSUE THREAD

**Issue by nisharga** [timolins/react-hot-toast#364]
**Before using react-hot-toast**

![Screenshot_96](https://github.com/timolins/react-hot-toast/assets/34031225/c330f339-c8d0-4f7e-892f-0f9907f0a5bb)

**After using react-hot-toast**

![Screenshot_97](https://github.com/timolins/react-hot-toast/assets/34031225/6b6f8eb8-d9db-495d-bf57-108de81bf7d1)

I am using it on layout.tsx

**Comment by timolins** [comment]
That is interesting. I'm not able to reproduce this. Can you provide a reproduction?
