### ISSUE TITLE
Dismiss method stops working when using custom method with MUI Alert

### ISSUE THREAD

**Issue by bokisha** [timolins/react-hot-toast#370]
Libraries used:
@mui/material 5.15.10
@react-hot-toast 2.4.1

[Stackblitz](https://stackblitz.com/edit/react-starter-typescript-lnuvjm?file=App.tsx)

Steps to reproduce: 

1. Click on Open toast 
2. Toast will be shown in top right corner
3. Click on X button to close it
4. When closed manually, toasts will always remain visible (stacked one above another)

Expected behavior: 
Toast should dissapear.

When using remove, everything works as expected.

**Comment by mirague** [comment]
@timolins Did you abandon this project? 🙏

**Comment by Redmega** [comment]
Can confirm this is happening to me as well

**Comment by timolins** [comment]
I believe this may be the same issue as #128

**Comment by timolins** [comment]
This bug should be fixed with `2.5.1.`! Thanks for reporting.
