### ISSUE TITLE
How to use toast.promise but don't need error

### ISSUE THREAD

**Issue by QuangNguyen1607** [timolins/react-hot-toast#373]
Hello everyone, how can i use toast.promise but don't use error because i handled it error by axios.interceptors.response so i don't need it in toast.promise.

**Comment by fellypsantos** [comment]
so pass a empty handler

`error: () => {}`

**Comment by n33pm** [comment]
#179

**Comment by timolins** [comment]
Closing in favour of #42 and matching PR #179
