### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by idc77** [timolins/react-hot-toast#377]
I suggest to create an action where dependencies of this package are automatically upgraded.

For instance this uses React v18.2.0 where the current version is v18.3.1

I see this on other repos, where some bot auto checks current package versions and creates PRs.

**Comment by timolins** [comment]
Hi! I just updated the dev dependencies, but having auto-updates might be a good idea. That said, `react-hot-toast` only has goober as actual dependency, since React is just a peer dependencies.
