### ISSUE TITLE
Add option for className of main element

### ISSUE THREAD

**Issue by Kilian** [timolins/react-hot-toast#43]
I'd like to add a class to this div through the props/options:

https://github.com/timolins/react-hot-toast/blob/main/src/components/toaster.tsx#L28

So that I can use CSS to catch for example hover and update the CSS for that (in my case, I'm adding a timeout animation that I need to pause for all toasts on hover)

It doesn't look hard to add, so let me know if I can open a PR for this.

**Comment by Systerr** [comment]
In our case we also  want to adjust styles of internal div element (change position fixed to absolute). That's important for us, as our react app only part of main app and have no access to parent styles. With position fixed notifications go out of our container and mess up by Z-index (hidden by parent header). Class name of main element will fix it for us.

**Comment by Kilian** [comment]
So, I ended up fixing it by just wrapping the Toast component in a div with a classname, then using that classname. Also works :)
