### ISSUE TITLE
Unwanted peer dependency message

### ISSUE THREAD

**Issue by hudochenkov** [timolins/react-hot-toast#44]
When installing `react-hot-toast` (or running `npm install` in a project that already has `react-hot-toast`) the following warning is shown:

> npm WARN goober@2.0.28 requires a peer of csstype@^2.6.2 but none is installed. You must install peer dependencies yourself.

Documentation says nothing about need of `csstype`.

Maybe `react-hot-toast` should make it regular dependency if it's needed?

On the other note, there are users, who are using just headless mode, and they don't need neither `goober` or `csstype`.

**Comment by timolins** [comment]
Thanks for reporting. I guess we can add csstype as dependency, just like you mention. Since it's types only it shouldn't matter, other than giving you a better dev experience when styling.

**Comment by thien-do** [comment]
Sorry @timolins but I don't think https://github.com/timolins/react-hot-toast/commit/d60adb6501af27dd0d3bf9fde75498dd3ce253a5 fixes the issue in RHT's users. Since it's "dev" dependency, it's not installed when the user installs RHT as their dependencies, so the warn would still be there

Maybe it's better to:
- Put csstype as devdependency in the user's package.json
- Put csstype as dependency of RHT
- Ask goober to put csstype as their dependency instead of peer

**Comment by liamlows** [comment]
@thien-do @timolins sorry to pull this issue out of the dark but we are trying to clean up our repo/packages and see the same resolution error with yarn:
`react-hot-toast@npm:2.2.0 doesn't provide csstype, requested by goober`
Is the suggestion that csstype must be installed as a dependency on our end, or is adding it as a devDependency good enough?
Also it may be worthwhile to add this to the ReadME if so.
Thanks!

**Comment by thien-do** [comment]
> Is the suggestion that csstype must be installed as a dependency on our end, or is adding it as a devDependency good enough?

Hard to say without knowing the codebase, but I think the best bet is you should not be asked to have a dependency if you don't use it directly. This means the best option should be:

> Ask goober to put csstype as their dependency instead of peer

While the best workaround should be:

> Put csstype as devdependency in the user's package.json

**Comment by liamlows** [comment]
@thien-do ok i went ahead and added it as a dev dependency however I am still getting the same issue. The same resolution warning pops up. Any idea what to do here?

**Comment by thien-do** [comment]
oh if that's the case it seems Yarn (or whatever package manager you are using) is more strict these days. Look like we will need to fix it properly (so either from RHT or from Goober)

**Comment by mikecousins** [comment]
I'm running into this as well with latest yarn.
