### ISSUE TITLE
Loading toast is removed before resolving the promise.

### ISSUE THREAD

**Issue by iamanas20** [timolins/react-hot-toast#45]
I noticed a weird behavior when running a promise that takes fairly long (about 30s) the loading toast is automatically dismissed even before resolving the promise, when it's resolved the success toast appears.

Can you reproduce this? Try having a promise that takes about 30 or 40 seconds to execute.

```javascript
toast.promise(subtitlesPromise, {
  loading: 'Generating your subtitles, please wait...',
  success: 'Subtitles generated!',
  error: 'Error generating subtitles.',
});
```

Thanks Timo for this awesome library!

**Comment by iamanas20** [comment]
@timolins any updates on this?

**Comment by timolins** [comment]
Thanks for mentioning this. This is somewhat intended, I figured that I limit loading toasts to 30s to prevent them from getting stuck: https://github.com/timolins/react-hot-toast/blob/main/src/core/store.ts#L134

Looking back, it probably wasn't the best decision. I will change this to `Infinity` in the next release.

**Comment by iamanas20** [comment]
Yeah, I guess that's it. Thanks a lot, Timo!

**Comment by iamanas20** [comment]
I noticed it's still not merged, any updates @timolins ?

**Comment by timolins** [comment]
Yep, sorry for the delay. Currently planing out v1.1 which includes quite a few things I want to get right. I'll hope to release in the next couple of days.

**Comment by iamanas20** [comment]
Sure and thanks.

**Comment by iamanas20** [comment]
Any updates on this? @timolins
