### ISSUE TITLE
Server error when using with Nextjs

### ISSUE THREAD

**Issue by exlane** [timolins/react-hot-toast#46]
Has anyone faced an issue when setting a position attribute to Toaster component? Error looks like 'Error: Objects are not valid as a React child (found: object with keys {position}). If you meant to render a collection of children, use an array instead.'

**Comment by timolins** [comment]
The example page is based on Next.js and I'm not experiencing any issues. Could you provide an example to reproduce?

**Comment by WebManifestation** [comment]
@exlane All you need to do is restart the dev server

**Comment by timolins** [comment]
Seems like this is resolved.

**Comment by nattawat-wib** [comment]
> @exlane All you need to do is restart the dev server

it also work for me. but can you explain why it work, or what about bug this error

**Comment by wajeshubham** [comment]
> > @exlane All you need to do is restart the dev server
> 
> it also work for me. but can you explain why it work, or what about bug this error

Same here. Can anybody please explain why restarting the dev server resolved the issue?

**Comment by hilookas** [comment]
> @exlane您需要做的就是重新启动开发服务器

Also works for Hydration Error

**Comment by alextaymx** [comment]
Can anybody explain why ?

**Comment by NotNullDev** [comment]
Dynamic import resolved hydration error permanently in my case:
```ts
import ...

const Toaster = dynamic(
  () => import("react-hot-toast").then((c) => c.Toaster),
  {
    ssr: false,
  }
);

const MyApp: AppType<{ session: Session | null }> = ({
  Component,
  pageProps: { session, ...pageProps },
}) => {
  return (
    <SessionProvider session={session}>
      <Toaster />
      <div className="container mx-auto min-h-screen">
        <Header />
        <Component {...pageProps} />
        <Footer />
      </div>
      <GlobalModalPortal />
    </SessionProvider>
  );
};
```

I thinks it may be due to used library css-in-js library (goober).
Here is  [goober example link](https://github.com/vercel/next.js/tree/canary/examples/with-goober) from [Nextjs docs about hydration error](https://nextjs.org/docs/messages/react-hydration-error).

**Comment by feihuan1** [comment]
restart server doen't work
