### ISSUE TITLE
Are there onEnter/onExit events or similar?

### ISSUE THREAD

**Issue by aesign** [timolins/react-hot-toast#47]
I'd love to blur the header of my website while the toast is in viewport, just like your website! Thank you.

**Comment by timolins** [comment]
Hi! While there are no onEnter/onExit events, you can replicate this effect by using the [`useToasterStore()`](https://react-hot-toast.com/docs/use-toaster-store) hook.

It returns you all current toasts, so you could implement a condition that only blurs when toasts are visible. This is how I did it on the website: https://github.com/timolins/react-hot-toast/blob/main/site/pages/index.tsx#L102

Here's a minimal example:

```js
  const { toasts } = useToasterStore();

  const visibileToasts = toasts.filter((t) => t.visible)
  const shouldFade = visibileToasts.length !== 0;
```

This could be paired with `useEffect()` to react to changes.
