### ISSUE TITLE
toast.dimiss

### ISSUE THREAD

**Issue by gr-qft** [timolins/react-hot-toast#50]
Thanks for this great library! 

I think this is more like a question. When `toast.dismiss` is called, a toast is dismissed after 1s, but if a new toast is created fast enough after `dismissed` is called, the toast will be dismissed almost immediately. Should creating a new toast be disabled while the dismissing animation is still in effect?

**Comment by timolins** [comment]
Great catch, this seems to be a bug. The remove timeout is not getting cleared when a new toast with the same ID is dispatched.
