### ISSUE TITLE
Avoid exposing `dispatch` from the library

### ISSUE THREAD

**Issue by frankdilo** [timolins/react-hot-toast#59]
Hi, thanks for this amazing library.

I have noticed that you expose your internal implementation of `dispatch`. Haven't investigated if there is a proper reason for doing this, but from the DX point of view it's terrible because all projects that use Redux with VS Code will import it by mistake when what they want to do is really: 

```js
const { dispatch } = props;
```

or 

```js
const dispatch = useDispatch();
```

I would consider not exporting your lib's internal dispatch to outside users of the lib.

**Comment by timolins** [comment]
Oh, that's a valid point. Haven't thought about that. There is no real reason why it's exported other giving people more control if they want. I think I'll remove the export with the next release and wait until someone requests it.
