### ISSUE TITLE
Toast position relative to container?

### ISSUE THREAD

**Issue by devstarman** [timolins/react-hot-toast#60]
No matter where Toaster is placed its' position is relative to the main document, is there a way to make it relative to the specific container?

For example if I have this structure:
```
<div className='main'>
   <div className='leftMenu'>
   </div>
   <div className='content'>
      <Toaster />
   </div>
</div>
```
and let's say leftMenu have 20% width and mainContent have 80% width, I wish centered toast would appear center to the 'content' - so 60% from left side of the screen, not relative to 'mainWrapper' (50% from left side of the screen).

**Comment by timolins** [comment]
This is currently not possible with the way toasts are positioned. I will consider this for future releases.
