### ISSUE TITLE
No default Export

### ISSUE THREAD

**Issue by miguel-krasamo** [timolins/react-hot-toast#65]
I'm getting an issue where the *.d.ts file doesn't have a default export and I'm getting the next error:

ERROR in [at-loader] ./node_modules/react-hot-toast/dist/components/toaster.d.ts:2:8 
    TS1192: Module '"/.../node_modules/csstype/index"' has no default export.

**Comment by timolins** [comment]
Can you provide an example that reproduces this behaviour?

**Comment by miguel-krasamo** [comment]
Yes, I don't remember if I commented in another issue where you said you will remove CSSType dependency.
I'm trying to follow best practices with typescript. Even if I know that I can change my eslint and tsconfig to not be so restrictive on imports.

.eslintrc
```
...
"settings": {
    "import/resolver": {
      "typescript": {
        "alwaysTryTypes": true,
        "project": "./tsconfig.json"
      }
    }
  },
  ...
```

And tsconfig.json hast ```strict: true```

So when using react hot toast I get the error which prevents the hot module reload (And I think once the project has it's own pipelines will fail due to it).

issue is with the file ```toaster.d.ts```
where line ```import CSS from 'csstype';``` should be ```import * as  CSS from 'csstype';```

**Comment by timolins** [comment]
Have you tried this with 2.0.0? It should no longer depend on csstype. https://github.com/timolins/react-hot-toast/commit/e58d6a8690e3329dcf2cbd2d7ac3c156a2e7a5b9

**Comment by miguel-krasamo** [comment]
I'm relying on yarn-check to update packages and it's not showing a new version for this but I already updated it and is working properly in 2.0.0
