### ISSUE TITLE
set z index

### ISSUE THREAD

**Issue by gmwill934** [timolins/react-hot-toast#68]
I am currently using the modals provided by `react semantic ui`. There is a prop for a modal which makes the blurred. (https://react.semantic-ui.com/modules/modal/). 

When I use it, my toasts won't appear, they are "behind" the blurred content. Is there a way to set the z index on the toasts or make them available up front?

**Comment by ZachHaber** [comment]
It's actually way more complicated than it needs to be. I couldn't figure out a way to set up the default Toaster component to use a className or a style.

Essentially, you need to `Portal` the `Toaster` into the `body`, and then set the Toaster to have `filter: unset`. Since we can't supply a style/class to the Toaster, I put a div around it to get rid of the blur.

Relevant code:

```
    <Portal open>
      <div style={{ filter: "unset" }}>
        <Toaster />
      </div>
    </Portal>
```
Running example:
https://codesandbox.io/s/suir-dimmer-hot-toast-ek2nb?file=/index.js

**Comment by timolins** [comment]
Yes, you can change the `z-index`, for both the container or the toasts. 

```jsx
<Toaster
  containerStyle={{
	 zIndex: 9999 // For the container
  }}
  toastOptions={{
    style: {
      zIndex: 9999 // For toasts
    },
  }}
/>
```

**Comment by jorisw** [comment]
What if you're using `toast.custom()` ? I still get a container with `z-index: 9999`, that I need to increase.

**Comment by timolins** [comment]
Yes, you can use container styles or manually add your `zIndex` to your custom component.

```jsx
toast.custom(<div style={{ zIndex: 9999 }}> {/ * Custom* /} </div>)
```

**Comment by jorisw** [comment]
However `toast.custom()`'s second parameter does not accept a `containerStyle` property:

![image](https://user-images.githubusercontent.com/30017/143927027-f0e6de40-38ed-4aac-8b15-ccaa3c20a479.png)

The styles that I apply myself to the top-level DOM node that my `<Notification />` component produces, does not help, as the container produced one level above, by `react-hot-toast`, sets a `z-index: 9999`, which I can't seem to override.

Even this doesn't work for me: 

```jsx
    toast.custom(<div style={{ zIndex: 20000, backgroundColor: 'red' }} />)
```

... The top level container of `react-hot-toast` keeps `z-index: 9999`.

**Comment by jorisw** [comment]
If the container element that `react-hot-toast` adds to the body, had an id or class name, at least I could override it using some global CSS and `!important`. But it's pretty much unselectable through CSS:

![image](https://user-images.githubusercontent.com/30017/144830242-a0ff0202-6677-43fb-ae34-ae14ae52fc5f.png)

**Comment by sanelaxm** [comment]
> However `toast.custom()`'s second parameter does not accept a `containerStyle` property:
> 
> ![image](https://user-images.githubusercontent.com/30017/143927027-f0e6de40-38ed-4aac-8b15-ccaa3c20a479.png)
> 
> The styles that I apply myself to the top-level DOM node that my `<Notification />` component produces, does not help, as the container produced one level above, by `react-hot-toast`, sets a `z-index: 9999`, which I can't seem to override.
> 
> Even this doesn't work for me:
> 
> ```js
>     toast.custom(<div style={{ zIndex: 20000, backgroundColor: 'red' }} />)
> ```
> 
> ... The top level container of `react-hot-toast` keeps `z-index: 9999`.

Were you able to get around this?

**Comment by joriswitteman** [comment]
Got around it by lowering other z indexes.
