### ISSUE TITLE
Question: how to Set top position

### ISSUE THREAD

**Issue by Aarbel** [timolins/react-hot-toast#70]
We need to make this UI :

![image](https://user-images.githubusercontent.com/25119847/115409079-b624fe00-a1f1-11eb-977a-1cc2e45aaf29.png)

Is there a way to set custom top position (in case of top-center position)

**Comment by lsbyerley** [comment]
I am wondering this too. We need to set the `top` position of the Toaster _container_ and it doesn't appear you can do this

**Comment by timolins** [comment]
Yes, this is possible. You can add a margin-top to your toast styles. 

See https://react-hot-toast.com/docs/styling → Changing the offset.


But be aware: This one of the few breaking changes with the up coming 2.0 release, which will support `top: 10px`, just like @lsbyerley suggested.

**Comment by Aarbel** [comment]
ok thanks a lot !

**Comment by lsbyerley** [comment]
@timolins thank you for the reply. This doesn't actually solve the issue of the `position:fixed` outer container covering up "Participants" link above the toast in the screenshot above. If you tried clicking on that link while the toast was open, it wouldn't not click.. I'm interested to see if this changes in v2

**Comment by RobSchilderr** [comment]
> @timolins thank you for the reply. This doesn't actually solve the issue of the `position:fixed` outer container covering up "Participants" link above the toast in the screenshot above. If you tried clicking on that link while the toast was open, it wouldn't click.. I'm interested to see if this changes in v2

have you managed to fix this? I am struggling to define a custom position with an offset. In my scenario, I have a capacitor iOS app and am using ```   style: {
      marginTop: 'env(safe-area-inset-top)',
    },``

but I'd actually want to use something like: 
```    className: 'top-[calc(0%_+_safe-area-inset-top)] ,
```
To get the offset if you understand me. Also the custom position doesnt work in my scenario.

**Comment by alexnb** [comment]
I am also interested in a solution for this.

**Comment by alexnb** [comment]
It looks like this was solved by specifying 
`
      <Toaster
        containerStyle={{ top: 100 }}
        toastOptions={{ position: "top-center" }}
      ></Toaster>
`

This positions the container at 100px from the top.
