### ISSUE TITLE
containerStyle prop in Toaster

### ISSUE THREAD

**Issue by lsbyerley** [timolins/react-hot-toast#71]
I need to customize some of the styling for the toast container. I don't see anything in the documentation, but I found `containerStyle` in the Toaster component below, however, it doesn't seem to do anything when passing it into the Toaster component. 

Is there a reason this is here?

https://github.com/timolins/react-hot-toast/blob/7e4391db1908ff0168bacd87beda115408b76ce0/src/components/toaster.tsx#L32

**Comment by lsbyerley** [comment]
So, it turns out, I actually need to be able to "inside container" of the toaster, as opposed to the "outer container" which is what `containerStyle` references.

The "inside container" is in the toast-bar component:
https://github.com/timolins/react-hot-toast/blob/351e62ab6248a41cd7267e74e710c27ca081aacc/src/components/toast-bar.tsx#L130

Would you accept a PR adding this style config?

**Comment by wjureczka** [comment]
Same here!

**Comment by timolins** [comment]
The "positioning div" you mentioned will be lifted up from the <ToastBar/> to the <Toaster/> with the next release. What are you trying to achieve?

**Comment by timolins** [comment]
2.0 is out now. You can read about the changes here: https://react-hot-toast.com/docs/version-2

It changes the behaviour how the Toaster is positioned, which might resolve the issues you had.
I'll close this issue for now, feel free to reopen if the problem remains.
