### ISSUE TITLE
Set duration for dismiss-able toast

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [timolins/react-hot-toast#77]
Hi, Looks like when set duration of toast (for my case `toast.error()`) it's not dismiss-able by click on toast.
```javascript
toast.error(
  "oh, error!",
  { duration: 1000 * 60 }
);
```

**Comment by timolins** [comment]
You are right, toasts are currently not dismissable by default. You'd have to implement your own close button for now. You can read more about it here: https://react-hot-toast.com/docs/toast-bar#add-custom-content

I have plans to add a default dismiss option. The related issue is #7.

**Comment by Absleepy** [comment]
@timolins I still don't see any option for closing on click.
