### ISSUE TITLE
Infinite duration does not work, toasts dismiss instantly

### ISSUE THREAD

**Issue by garand** [timolins/react-hot-toast#79]
Hey! I saw this PR https://github.com/timolins/react-hot-toast/pull/37 and tried out a duration of `Infinity`, but it is just causing the toast to dismiss instantly.

I've put together a CodeSandbox that reproduces the behavior. Any ideas?

https://codesandbox.io/s/pedantic-framework-c3v0x?file=/src/App.js

**Comment by garand** [comment]
Ah, it looks like there hasn't been a new version published since that. That would probably be why.

**Comment by timolins** [comment]
You can try out `react-hot-toast@2.0.0-beta.0` which includes this fix :) Will be publicity released after I gather some feedback.

**Comment by timolins** [comment]
Fix is out now with 2.0.0!

**Comment by shubham-mcsam** [comment]
The exact same issue of is occurring in 2.2.0

**Comment by timolins** [comment]
@shubham-mcsam Can you share an example that reproduces this issue?

**Comment by shubham-mcsam** [comment]
My bad, it's working as expected. I was writing Infinity as a string! Thanks for your work on the library
